version: "0.2"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install -r backend/requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build commands"

  build:
    commands:
      - echo "Running tests (if applicable)"
      # Add your test commands here, for example:
      # - python -m unittest discover tests/

  post_build:
    commands:
      - echo "Running post-build commands"

artifacts:
  files: "**/*"
  discard-paths: yes

cache:
  paths:
    - "/root/.cache/pip/**/*"

